version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    container_name: backend
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    container_name: frontend
    restart: on-failure
    ports:
      - "3001:80"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    volumes:
      - ./../mongodb-data:/data/db

volumes:
  mongodb-data:
